<a href="https://colab.research.google.com/github/praveenm-web/NASSCOM/blob/main/Day2_NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")
# 1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.
arr1_1 = np.arange(100)
print("arr1_1:\n", arr1_1)

# 1.2 Create a 3x3 array named 'arr1_2' filled with ones.
arr1_2 = np.ones((3, 3))
print("\narr1_2:\n", arr1_2)

# 1.3 Create a 2x4 array named 'arr1_3' filled with the number 7.
arr1_3 = np.full((2, 4), 7)
print("\narr1_3:\n", arr1_3)

# 1.4 Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).
arr1_4 = np.random.randint(10, 51, size=(5, 5))
print("\narr1_4:\n", arr1_4)


--- Task 1: Array Creation Shortcuts ---
arr1_1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]

arr1_4:
 [[38 43 15 31 47]
 [28 41 50 25 36]
 [45 48 42 13 48]
 [11 23 33 18 12]
 [28 16 40 35 14]]


In [4]:
import numpy as np

# Create a sample 'data' array for tasks 2.1-2.5
# Assuming a 5x5 array with random integers between 1 and 150 for demonstration
data = np.random.randint(1, 151, size=(5, 5))
print("\n--- Task 2: Array Indexing and Slicing ---")
print("Original 'data' array:\n", data)

# 2.1 Extract the element at row 2, column 3 (0-indexed). Store it in 'val2_1'.
val2_1 = data[2, 3]
print(f"\n2.1 Element at row 2, col 3: {val2_1}")

# 2.2 Extract the first row. Store it in 'row2_2'.
row2_2 = data[0, :]
print("\n2.2 First row:\n", row2_2)

# 2.3 Extract the last column. Store it in 'col2_3'.
col2_3 = data[:, -1]
print("\n2.3 Last column:\n", col2_3)

# 2.4 Extract the sub-array consisting of rows 1 and 2, and columns 0 and 1. Store it in 'sub_arr2_4'.
sub_arr2_4 = data[1:3, 0:2]
print("\n2.4 Sub-array (rows 1-2, cols 0-1):\n", sub_arr2_4)

# 2.5 Using boolean indexing, select all elements in 'data' that are greater than 100. Store them in 'filtered_elements2_5'.
filtered_elements2_5 = data[data > 100]
print("\n2.5 Elements greater than 100:\n", filtered_elements2_5)


--- Task 2: Array Indexing and Slicing ---
Original 'data' array:
 [[ 23 139  44  64  99]
 [ 86 144  19  97  66]
 [ 83 118 109 139 128]
 [128 117  18  54  96]
 [ 25  51 129 126   8]]

2.1 Element at row 2, col 3: 139

2.2 First row:
 [ 23 139  44  64  99]

2.3 Last column:
 [ 99  66 128  96   8]

2.4 Sub-array (rows 1-2, cols 0-1):
 [[ 86 144]
 [ 83 118]]

2.5 Elements greater than 100:
 [139 144 118 109 139 128 128 117 129 126]


In [5]:
import numpy as np

print("\n--- Task 3: Conditional Operations and Counting ---")
# Create a sample array 'arr3_1' for demonstration
arr3_1 = np.random.randint(0, 20, size=(4, 5))
print("Original arr3_1:\n", arr3_1)

# 3.1 Create a new array 'arr3_2' where elements in 'arr3_1' less than 10 are replaced with 0,
#     and elements greater than or equal to 10 remain unchanged.
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)
print("\nArr3_2 (elements < 10 replaced with 0):\n", arr3_2)

# 3.2 Count how many elements in 'arr3_1' are even. Store the count in 'even_count3_3'.
even_count3_3 = np.sum(arr3_1 % 2 == 0)
print(f"\nNumber of even elements in arr3_1: {even_count3_3}")


--- Task 3: Conditional Operations and Counting ---
Original arr3_1:
 [[19 11  1 17  5]
 [17 18 15 14 17]
 [ 0 18 17  2 12]
 [ 6 10 12 10  6]]

Arr3_2 (elements < 10 replaced with 0):
 [[19 11  0 17  0]
 [17 18 15 14 17]
 [ 0 18 17  0 12]
 [ 0 10 12 10  0]]

Number of even elements in arr3_1: 11


In [6]:
import numpy as np

print("\n--- Task 4: Array Aggregations ---")
# Create a sample array 'arr4_1' for demonstration
arr4_1 = np.random.randint(1, 101, size=(5, 4)) # Example 5x4 array with values from 1 to 100
print("Original arr4_1:\n", arr4_1)

# 4.1 Calculate the sum of all elements in 'arr4_1'. Store it in 'sum4_1'.
sum4_1 = np.sum(arr4_1)
print(f"\n4.1 Sum of all elements: {sum4_1}")

# 4.2 Calculate the mean of each column. Store it in 'mean_cols4_2'.
mean_cols4_2 = np.mean(arr4_1, axis=0)
print(f"\n4.2 Mean of each column: {mean_cols4_2}")

# 4.3 Find the maximum value in each row. Store it in 'max_rows4_3'.
max_rows4_3 = np.max(arr4_1, axis=1)
print(f"\n4.3 Maximum value in each row: {max_rows4_3}")

# 4.4 Calculate the standard deviation of the entire array. Store it in 'std4_4'.
std4_4 = np.std(arr4_1)
print(f"\n4.4 Standard deviation of the entire array: {std4_4}")


--- Task 4: Array Aggregations ---
Original arr4_1:
 [[81 11  5 53]
 [96 28 25 21]
 [38  3 22 75]
 [77 97 18  3]
 [23 37 27 88]]

4.1 Sum of all elements: 828

4.2 Mean of each column: [63.  35.2 19.4 48. ]

4.3 Maximum value in each row: [81 96 75 97 88]

4.4 Standard deviation of the entire array: 31.54900949316793


In [7]:
import numpy as np

print("\n--- Task 5: Array Reshaping and Flattening ---")
# Create a sample 1D array 'arr5_1' with 24 elements for demonstration
arr5_1 = np.arange(24)
print("Original arr5_1 (1D):\n", arr5_1)

# 5.1 Reshape 'arr5_1' into a 4x6 2D array. Store it in 'reshaped_arr5_2'.
reshaped_arr5_2 = arr5_1.reshape(4, 6)
print("\nReshaped arr5_2 (4x6 2D):\n", reshaped_arr5_2)

# 5.2 Reshape 'arr5_1' into a 2x3x4 3D array. Store it in 'reshaped_arr5_3'.
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)
print("\nReshaped arr5_3 (2x3x4 3D):\n", reshaped_arr5_3)

# 5.3 Flatten 'reshaped_arr5_2' back into a 1D array. Store it in 'flattened_arr5_4'.
#     Use both `.ravel()` and `.flatten()` to see if there's a difference (though not visible in output).
flattened_arr5_4_ravel = reshaped_arr5_2.ravel()
flattened_arr5_4_flatten = reshaped_arr5_2.flatten()
print("\nFlattened arr5_4 (using .ravel()):\n", flattened_arr5_4_ravel)
print("Flattened arr5_4 (using .flatten()):\n", flattened_arr5_4_flatten)
# Note: .ravel() returns a view when possible, .flatten() always returns a copy.


--- Task 5: Array Reshaping and Flattening ---
Original arr5_1 (1D):
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Reshaped arr5_2 (4x6 2D):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Reshaped arr5_3 (2x3x4 3D):
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Flattened arr5_4 (using .ravel()):
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Flattened arr5_4 (using .flatten()):
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [8]:
# Task 6: Broadcasting
print("\n--- Task 6: Broadcasting ---")
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
vector = np.array([100, 200, 300])

# 6.1 Add the 'scalar' to every element of 'arr6_1'. Store it in 'result6_1'.
result6_1 = arr6_1 + scalar
print("\n6.1 arr6_1 + scalar:\n", result6_1)

# 6.2 Add the 'vector' to each row of 'arr6_1'. Store it in 'result6_2'.
result6_2 = arr6_1 + vector
print("\n6.2 arr6_1 + vector (row-wise broadcasting):\n", result6_2)

# Your code for Task 6 here:


--- Task 6: Broadcasting ---

6.1 arr6_1 + scalar:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

6.2 arr6_1 + vector (row-wise broadcasting):
 [[101 202 303]
 [104 205 306]
 [107 208 309]]


In [9]:
# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")
original_arr7 = np.array([1, 2, 3, 4, 5])
print("Original array before operations:\n", original_arr7)

# 7.1 Create a 'view' of 'original_arr7' named 'view_arr7' by slicing the entire array.
#     Modify the first element of 'view_arr7' to 99.
#     Observe how 'original_arr7' changes.
view_arr7 = original_arr7[:]
view_arr7[0] = 99
print("\n7.1 After modifying view_arr7:")
print("view_arr7:\n", view_arr7)
print("original_arr7 (modified via view):\n", original_arr7)

# 7.2 Create a 'copy' of 'original_arr7' named 'copy_arr7' using `.copy()`.
#     Modify the last element of 'copy_arr7' to 0.
#     Observe how 'original_arr7' remains unchanged.
copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0
print("\n7.2 After modifying copy_arr7:")
print("copy_arr7:\n", copy_arr7)
print("original_arr7 (unchanged by copy):\n", original_arr7)

# Your code for Task 7 here:


--- Task 7: Copying vs. Viewing Arrays ---
Original array before operations:
 [1 2 3 4 5]

7.1 After modifying view_arr7:
view_arr7:
 [99  2  3  4  5]
original_arr7 (modified via view):
 [99  2  3  4  5]

7.2 After modifying copy_arr7:
copy_arr7:
 [99  2  3  4  0]
original_arr7 (unchanged by copy):
 [99  2  3  4  5]


In [11]:
# Task 8: Stacking and Splitting Arrays
print("\n--- Task 8: Stacking and Splitting Arrays ---")
arr8_a = np.array([[1, 2]])
arr8_b = np.array([[3, 4]])
arr8_c = np.array([[5, 6]])

print("arr8_a:\n", arr8_a)
print("arr8_b:\n", arr8_b)
print("arr8_c:\n", arr8_c)

# 8.1 Vertically stack 'arr8_a' and 'arr8_b'. Store it in 'vstack_arr8_1'.
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))
print("\n8.1 Vertically stacked arr8_a and arr8_b (vstack_arr8_1):\n", vstack_arr8_1)

# 8.2 Horizontally stack 'arr8_a' and 'arr8_b'. Store it in 'hstack_arr8_2'.
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))
print("\n8.2 Horizontally stacked arr8_a and arr8_b (hstack_arr8_2):\n", hstack_arr8_2)

# 8.3 Vertically stack 'vstack_arr8_1' and 'arr8_c'. Store it in 'combined_arr8_3'.
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))
print("\n8.3 Vertically stacked vstack_arr8_1 and arr8_c (combined_arr8_3):\n", combined_arr8_3)

# 8.4 Split 'combined_arr8_3' into 3 equal parts (rows). Store them in 'part1', 'part2', 'part3'.
part1, part2, part3 = np.vsplit(combined_arr8_3, 3)
print("\n8.4 Splitting combined_arr8_3 into 3 parts:")
print("Part 1:\n", part1)
print("Part 2:\n", part2)
print("Part 3:\n", part3)

# Your code for Task 8 here:


--- Task 8: Stacking and Splitting Arrays ---
arr8_a:
 [[1 2]]
arr8_b:
 [[3 4]]
arr8_c:
 [[5 6]]

8.1 Vertically stacked arr8_a and arr8_b (vstack_arr8_1):
 [[1 2]
 [3 4]]

8.2 Horizontally stacked arr8_a and arr8_b (hstack_arr8_2):
 [[1 2 3 4]]

8.3 Vertically stacked vstack_arr8_1 and arr8_c (combined_arr8_3):
 [[1 2]
 [3 4]
 [5 6]]

8.4 Splitting combined_arr8_3 into 3 parts:
Part 1:
 [[1 2]]
Part 2:
 [[3 4]]
Part 3:
 [[5 6]]


In [12]:
# Task 9: Sorting and Searching
print("\n--- Task 9: Sorting and Searching ---")
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

print("Original arr9_1:\n", arr9_1)
print("Original arr9_2d:\n", arr9_2d)

# 9.1 Sort 'arr9_1' in ascending order. Store it in 'sorted_arr9_1'.
sorted_arr9_1 = np.sort(arr9_1)
print("\n9.1 Sorted arr9_1:\n", sorted_arr9_1)

# 9.2 Sort 'arr9_2d' along columns (i.e., each column sorted independently). Store it in 'sorted_cols9_2'.
sorted_cols9_2 = np.sort(arr9_2d, axis=0)
print("\n9.2 arr9_2d sorted along columns:\n", sorted_cols9_2)

# 9.3 Find the indices where the value 9 is present in 'arr9_1'. Store it in 'idx9_3'. (Hint: use np.where)
idx9_3 = np.where(arr9_1 == 9)
print("\n9.3 Indices where 9 is present in arr9_1:\n", idx9_3)

# 9.4 Find the index of the maximum value in 'arr9_1'. Store it in 'max_idx9_4'.
max_idx9_4 = np.argmax(arr9_1)
print("\n9.4 Index of maximum value in arr9_1:\n", max_idx9_4)

# Your code for Task 9 here:


--- Task 9: Sorting and Searching ---
Original arr9_1:
 [5 2 8 1 9 4 7 3 6]
Original arr9_2d:
 [[30 20 10]
 [60 50 40]
 [90 80 70]]

9.1 Sorted arr9_1:
 [1 2 3 4 5 6 7 8 9]

9.2 arr9_2d sorted along columns:
 [[30 20 10]
 [60 50 40]
 [90 80 70]]

9.3 Indices where 9 is present in arr9_1:
 (array([4]),)

9.4 Index of maximum value in arr9_1:
 4
